#!/usr/bin/env python3
"""Fetch the third-party speaker-verification sources and finetune checkpoint.

Nothing here is redistributed by this repository. Two upstream projects supply
the model code, and both are pinned by **content hash** rather than by branch,
so a silent upstream edit fails the fetch instead of quietly changing SIM:

    UniSpeech  (microsoft/UniSpeech)  ecapa_tdnn.py   -- the ECAPA speaker head
    WavLM      (microsoft/unilm)      WavLM.py, modules.py  (MIT)

The files land in a gitignored ``third_party/sv/`` laid out as a package whose
``utils`` module re-exports ``wavepainter.metrics.sim_model``. UniSpeech's
unmodified ``from .utils import UpstreamExpert`` then resolves to our shim --
its own documented extension point. No upstream file is edited.

    python scripts/fetch_sim_model.py [--dest third_party/sv]
"""

import argparse
import hashlib
import os
import sys
import urllib.request

UNISPEECH_REF = "40ac183e772abdcbf3a318eccffaa70c0cfd3a74"
UNILM_REF = "158b81152fff118ab45fb60bb076021716431153"


def _relativise_modules_import(text):
    """``from modules import`` -> ``from .modules import``.

    WavLM ships as a flat script directory; we import it as a package. This is
    the only edit made to any upstream file, it is purely about import
    resolution, and ``final_sha`` below proves it produced exactly the bytes the
    reported numbers came from.
    """
    return text.replace("\nfrom modules import (", "\nfrom .modules import (", 1)


# Each entry: url, sha256 of the file AS UPSTREAM SERVES IT, an optional
# transform, and the sha256 of the result. Both hashes are checked: the first
# catches upstream drift, the second proves the local file is byte-identical to
# what produced the published SIM column.
SOURCES = {
    "ecapa_tdnn.py": {
        "url": (
            f"https://raw.githubusercontent.com/microsoft/UniSpeech/{UNISPEECH_REF}"
            "/downstreams/speaker_verification/models/ecapa_tdnn.py"
        ),
        "upstream_sha": "9571bb524980c1447d64c4fadaa31a4772d0ca1e9864d523c091ed600ff134e6",
        "transform": None,
        "final_sha": "9571bb524980c1447d64c4fadaa31a4772d0ca1e9864d523c091ed600ff134e6",
    },
    "wavlm/WavLM.py": {
        "url": (
            f"https://raw.githubusercontent.com/microsoft/unilm/{UNILM_REF}"
            "/wavlm/WavLM.py"
        ),
        "upstream_sha": "c39e65f49c9027b330519c30a576700f4ef2e74ccda52f7f60f259d3aad0d343",
        "transform": _relativise_modules_import,
        "final_sha": "d1507c86739be50469024cb002851fa69626bce9a73e19ffe3472e64f7ebbb46",
    },
    "wavlm/modules.py": {
        "url": (
            f"https://raw.githubusercontent.com/microsoft/unilm/{UNILM_REF}"
            "/wavlm/modules.py"
        ),
        "upstream_sha": "7a06a14a7dc95c5f65cd6b09ed126013821512489dcfec2e58bd8b544ce46656",
        "transform": None,
        "final_sha": "7a06a14a7dc95c5f65cd6b09ed126013821512489dcfec2e58bd8b544ce46656",
    },
}

# The generated bridge. UniSpeech's ecapa_tdnn.py does `from .utils import
# UpstreamExpert`; this hands it ours. Generated rather than committed so that
# the package containing third-party files stays entirely gitignored.
UTILS_BRIDGE = '''"""Generated by scripts/fetch_sim_model.py -- do not edit.

Bridges UniSpeech's `from .utils import UpstreamExpert` to wavepainter's shim.
"""

from wavepainter.metrics.sim_model import UpstreamExpert, WAVLM_LARGE_CFG  # noqa: F401
'''

SV_CHECKPOINT_URL = (
    "https://huggingface.co/Dongchao/UniAudio/resolve/main/wavlm_large_finetune.pth"
)
SV_CHECKPOINT_NAME = "wavlm_large_finetune.pth"


def _download(url):
    with urllib.request.urlopen(url) as response:
        return response.read()


def _check(payload, expected_sha, url, what):
    actual = hashlib.sha256(payload).hexdigest()
    if expected_sha and actual != expected_sha:
        raise RuntimeError(
            f"{url}\n  {what} hash mismatch: expected {expected_sha}, got {actual}.\n"
            "  The reported SIM numbers were produced with the pinned revision; "
            "do not silently accept a different one -- check what changed first."
        )


def _fetch_source(relative, spec, dest):
    """Download a pinned source file, apply its transform, verify both hashes."""
    print(f"| fetching {relative}")
    payload = _download(spec["url"])
    _check(payload, spec["upstream_sha"], spec["url"], "upstream")

    if spec["transform"] is not None:
        payload = spec["transform"](payload.decode("utf-8")).encode("utf-8")
    _check(payload, spec["final_sha"], spec["url"], "post-transform")

    path = os.path.join(dest, relative)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(payload)


def _fetch_binary(url, dest):
    """Download a large file with no content pin (the checkpoint)."""
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    payload = _download(url)
    with open(dest, "wb") as handle:
        handle.write(payload)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dest", default="third_party/sv")
    ap.add_argument(
        "--checkpoint-dir",
        default="third_party",
        help="where to place the speaker-verification finetune checkpoint",
    )
    ap.add_argument(
        "--skip-checkpoint", action="store_true", help="fetch sources only"
    )
    args = ap.parse_args()

    dest = os.path.abspath(args.dest)
    for relative, spec in SOURCES.items():
        _fetch_source(relative, spec, dest)

    # Make it an importable package and install the bridge.
    for package_dir in (dest, os.path.join(dest, "wavlm")):
        init = os.path.join(package_dir, "__init__.py")
        if not os.path.exists(init):
            open(init, "w").close()
    with open(os.path.join(dest, "utils.py"), "w") as handle:
        handle.write(UTILS_BRIDGE)

    if not args.skip_checkpoint:
        checkpoint = os.path.join(
            os.path.abspath(args.checkpoint_dir), SV_CHECKPOINT_NAME
        )
        if os.path.exists(checkpoint):
            print(f"| checkpoint already present: {checkpoint}")
        else:
            print("| fetching wavlm_large_finetune.pth (~1.2 GB)")
            _fetch_binary(SV_CHECKPOINT_URL, checkpoint)
        print(f"| score with --sv_ckpt {checkpoint}")

    # Prove the assembled package imports before declaring success -- a missing
    # bridge or a moved upstream symbol should fail here, not mid-benchmark.
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    os.environ["WAVEPAINTER_SV_DIR"] = dest
    from wavepainter.metrics.sim_model import _import_third_party

    _import_third_party()
    print(f"| speaker-verification sources ready at {dest}")


if __name__ == "__main__":
    main()
