#!/usr/bin/env python3
"""Rebuild the training data: LibriTTS -> forced alignment -> binarised pack.

Only phase 1 needs this. Phase 2 trains from the released base checkpoint on the
same binarised pack, so if you are reproducing the contribution rather than
rebuilding the editor from scratch, you need this too -- but nothing below is
required merely to *score* the released model, which reads the benchmark instead.

    python scripts/prepare_data.py --all

Stages, each runnable alone:

    --download    LibriTTS train-clean-100 (CC BY 4.0, ~6 GB) into data/raw
    --align       Montreal Forced Aligner over the corpus  -> TextGrids
    --preprocess  text normalisation, phone set, speaker map
    --binarize    the packed mel/f0/duration archive the trainer reads

THE VOCABULARIES ARE NOT REGENERATED BY DEFAULT. `assets/vocab/phone_set.json`,
`spk_map.json` and `word_set.json` ship frozen, and `--preprocess` copies them
into place rather than deriving new ones. This matters: the phone set's ORDER
determines token ids, and a regenerated set that orders phones differently
produces a vocabulary the released checkpoints' embedding table does not match.
Nothing raises -- the model simply reads the wrong phone for every token. Pass
`--regenerate-vocab` only if you intend a genuinely fresh vocabulary and accept
that the released weights no longer apply.
"""

import argparse
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBRITTS_URL = "https://www.openslr.org/resources/60/train-clean-100.tar.gz"
MFA_ACOUSTIC = "english_mfa"
MFA_DICT = "english_us_mfa"
FROZEN_VOCAB = ("phone_set.json", "spk_map.json", "word_set.json", "mfa_dict.txt")


def run(cmd, **kw):
    print(f"|  $ {' '.join(cmd)}")
    subprocess.run(cmd, check=True, cwd=ROOT, **kw)


def download(raw_dir):
    os.makedirs(raw_dir, exist_ok=True)
    tarball = os.path.join(raw_dir, "train-clean-100.tar.gz")
    if os.path.exists(os.path.join(raw_dir, "LibriTTS")):
        print("| LibriTTS already present")
        return
    if not os.path.exists(tarball):
        print(f"| downloading LibriTTS train-clean-100 (~6 GB)")
        run(["curl", "-L", "-o", tarball, LIBRITTS_URL])
    run(["tar", "-xzf", tarball, "-C", raw_dir])


def align(raw_dir, out_dir):
    """Forced-align with MFA. The TextGrids are what mel2ph is built from."""
    if shutil.which("mfa") is None:
        raise SystemExit(
            "Montreal Forced Aligner not found. Install it "
            "(conda install -c conda-forge montreal-forced-aligner), then rerun."
        )
    run(["mfa", "model", "download", "acoustic", MFA_ACOUSTIC])
    run(["mfa", "model", "download", "dictionary", MFA_DICT])
    os.makedirs(out_dir, exist_ok=True)
    run(["mfa", "align", raw_dir, MFA_DICT, MFA_ACOUSTIC, out_dir, "--clean"])


def preprocess(regenerate_vocab):
    run([sys.executable, "-m", "wavepainter.datasets.base_preprocess", "libritts"])
    if regenerate_vocab:
        print("| WARNING: regenerated vocabularies -- the released checkpoints "
              "no longer apply to this data")
        return
    processed = os.path.join(ROOT, "data", "processed", "libritts")
    os.makedirs(processed, exist_ok=True)
    for name in FROZEN_VOCAB:
        src = os.path.join(ROOT, "assets", "vocab", name)
        if os.path.exists(src):
            shutil.copy(src, os.path.join(processed, name))
            print(f"|  restored frozen {name}")


def binarize(config):
    run([sys.executable, "-m", "wavepainter.datasets.base_binarizer", "--config", config])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--all", action="store_true", help="every stage in order")
    ap.add_argument("--download", action="store_true")
    ap.add_argument("--align", action="store_true")
    ap.add_argument("--preprocess", action="store_true")
    ap.add_argument("--binarize", action="store_true")
    ap.add_argument("--align-benchmark", action="store_true",
                    help="align the benchmark audio instead of LibriTTS")
    ap.add_argument("--regenerate-vocab", action="store_true",
                    help="derive a fresh phone/speaker vocabulary (see the note above)")
    ap.add_argument("--raw-dir", default=os.path.join(ROOT, "data", "raw", "libritts"))
    ap.add_argument("--config", default="configs/base.yaml")
    args = ap.parse_args()

    if args.align_benchmark:
        bench = os.environ.get("WAVEPAINTER_BENCHMARK",
                               os.path.join(ROOT, "data", "ming"))
        print(
            "NOTE: you do not need this to reproduce the reported numbers.\n"
            "  The 655 alignments the results were produced with SHIP in\n"
            "  assets/alignments/ and are what evaluate.py uses by default.\n"
            "  Re-aligning here produces a DIFFERENT set: the MFA version and\n"
            "  dictionary used originally were never pinned, and the orthography\n"
            "  fixes that let 25 otherwise-unalignable items through are not\n"
            "  reproduced by this path. Use it to align new data, not to\n"
            "  regenerate the benchmark.\n"
        )
        # The published dataset lays audio out at `wavs/`; there is no `audio/`.
        align(os.path.join(bench, "wavs"),
              os.path.join(bench, "mfa_outputs_regenerated"))
        return

    stages = [args.download, args.align, args.preprocess, args.binarize]
    if args.all or not any(stages):
        args.download = args.align = args.preprocess = args.binarize = True

    if args.download:
        download(args.raw_dir)
    if args.align:
        align(args.raw_dir, os.path.join(ROOT, "data", "processed", "libritts", "mfa_outputs"))
    if args.preprocess:
        preprocess(args.regenerate_vocab)
    if args.binarize:
        binarize(args.config)
    print("| data ready")


if __name__ == "__main__":
    main()
